// This file is autogenerated. Changes will be overwritten.
// No files found that require moc or the moc files are included
struct cmake_automoc_silence_linker_warning{
    virtual ~cmake_automoc_silence_linker_warning();
};

inline cmake_automoc_silence_linker_warning::~cmake_automoc_silence_linker_warning()
{}
